version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: "no"
    ports:
      - 15672:15672
      - 5672:5672
  orcldb:
    container_name: orcldb
    build:
      dockerfile: ./Dockerfile
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      DB_SID: xe
      DB_MEMORY: 4GB
    volumes:
      - ./startup/scripts:/home/oracle/setup/custom_scripts
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "YES"